version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

  app:
    container_name: app
    build:
      dockerfile: app.Dockerfile
    image: app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    restart: always

volumes:
  db: